### ISSUE TITLE
improved routing rules

### ISSUE THREAD

**Issue by hmoffatt** [kkinder/wsgigo#1]
Thanks for this code. It was really helpful for me to combine two WSGI applications.

I have two little suggestions:

- The startswith rule could optionally strip the prefix from the path
- Allow regular expression matching, which again could optionally replace the path with a group returned by the regular expression match

I needed to look for a prefix of '/gw/<something>' and strip it off before passing it on to the application so I wrote a new rule class which does this:

```python
        class GatewayRouter(wsgigo.Route):
            def claim(self, environ):
                match = re.match(r'/gw/[-\w]+(/.*)', environ['PATH_INFO'])
                if match:
                    environ['PATH_INFO'] = match.group(1)
                    return True
```

**Comment by kkinder** [comment]
Thanks!

Can you elaborate on 'strip the prefix from the path'? I'm not sure what prefix you mean by that. What's an example of a route you'd want to match?

I certainly wrote it with the idea in mind that you could write your own routes that claim routes using other rules. I guess besides personal preference, the only reason I left out regex's is that I had in mind the idea that you would probably end up sticking to fairly unique prefixes for each wsgi destination. Obviously that won't always be the case. Want to throw that class in a pull request and I'll add it?

**Comment by hmoffatt** [comment]
I just added a PR with the strip functionality. The idea was that I can have /app1/foo and /app2/bar, but the two applications just see the URL as /foo and /bar respectively. They don't have to be modified to know about the extra layer of routing in front of them.

I'm just using the regexp because I want to match /prefix/*/path and pass that on as /path to the underlying application. It might not be of general interest but I'll put together another PR anyway.

**Comment by kkinder** [comment]
#3 and #2 

merged.

**Comment by hmoffatt** [comment]
Thanks!
